export const UPDATE_SESSION_ID = "UPDATE_SESSION_ID";
export const UPDATE_USER = "UPDATE_USER";
export const SHOW_LOGIN_MODAL = "SHOW_LOGIN_MODAL";
export const LOGOUT = "LOGOUT";
export const UPDATE_FAVORITE_MOVIES = "UPDATE_FAVORITE_MOVIES";
export const UPDATE_WATCHLIST_MOVIES = "UPDATE_WATCHLIST_MOVIES";
