export const UPDATE_AUTH = "UPDATE_AUTH";
export const SHOW_LOGIN_MODAL = "SHOW_LOGIN_MODAL";
export const LOGOUT = "LOGOUT";
export const UPDATE_FAVORITE_MOVIES = "UPDATE_FAVORITE_MOVIES";
export const UPDATE_WATCHLIST_MOVIES = "UPDATE_WATCHLIST_MOVIES";
