export const FETCH_SUCCESS_AUTH = "FETCH_SUCCESS_AUTH";
export const SHOW_LOGIN_MODAL = "SHOW_LOGIN_MODAL";
export const LOGOUT = "LOGOUT";
export const UPDATE_FAVORITE_MOVIES = "UPDATE_FAVORITE_MOVIES";
export const UPDATE_WATCHLIST_MOVIES = "UPDATE_WATCHLIST_MOVIES";
export const FETCH_REQUEST_AUTH = "FETCH_REQUEST_AUTH";
export const FETCH_ERROR_AUTH = "FETCH_ERROR_AUTH";
